name: coverage
on: push

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-- --test-threads 1'

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

      - uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml
